python create_sub_nl.py --dataset ../data/CODEX --gen_train
python create_sub_nl.py --dataset ../data/UMLS --gen_train
python create_sub_nl.py --dataset ../data/FB15k-237 --gen_train
python create_sub_nl.py --dataset ../data/CODEX --gen_valid
python create_sub_nl.py --dataset ../data/UMLS --gen_valid
python create_sub_nl.py --dataset ../data/FB15k-237 --gen_valid
python create_sub_nl.py --dataset ../data/CODEX --gen_test
python create_sub_nl.py --dataset ../data/UMLS --gen_test
python create_sub_nl.py --dataset ../data/FB15k-237 --gen_test